### PR TITLE
LPS-52807 No files to choose in web content when using documentum

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
To Brian: this should be backported to ee-7.0.x and ee-6.2.x directly. If you can't do it, tell me and I'll send you a PR. Thx.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Lo vemos mañana porque hay una cosilla que no termino de entender el motivo del cambio...

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4159. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
